version: '3'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always

  proxy:
    depends_on:
    - backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "80:80"